# docker-compose.yml
# ------------------
services:
  together_api:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
      - COMPOSER_PROCESS_TIMEOUT=900
      - COMPOSER_AUTH={"github-oauth":{"github.com":"${GITHUB_TOKEN}"}}
      - GIT_SSH_COMMAND=ssh -o StrictHostKeyChecking=no
    volumes:
      - ./:/var/www/html
      - ${HOME}/.ssh:/root/.ssh:ro
      - ${HOME}/.composer:/root/.composer
      - ./docker/nginx/api.conf:/etc/nginx/conf.d/api.conf
      - ./docker/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
    ports:
      - "80:80"
      - "443:443"
    networks:
      - laravel

  together_db:
    image: mariadb:lts
    container_name: together_db
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: together
      MARIADB_USER: laravel
      MARIADB_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - laravel
    volumes:
      - './docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
      - db_data:/var/lib/mysql

networks:
  laravel:
    driver: bridge

volumes:
  db_data:
