FROM nginx:alpine

# Copy custom Nginx config
COPY ./docker/nginx/default.conf /etc/nginx/conf.d/default.conf

# Set working directory to Laravel public
WORKDIR /var/www/html

# Nginx runs as foreground by default
