[supervisord]
nodaemon=true
user=root

[program:mariadb]
command=/usr/sbin/mysqld --user=mysql
autorestart=true
priority=5

[program:php-fpm]
command=/usr/local/sbin/php-fpm
autorestart=true
priority=10

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autorestart=true
priority=20

[program:queue-worker]
command=php /var/www/html/artisan queue:work --sleep=3 --tries=3 --max-time=3600
directory=/var/www/html
user=www-data
autorestart=true
priority=30
stdout_logfile=/var/log/queue-worker.log
stderr_logfile=/var/log/queue-worker.log
